darwinia-network/darwinia-messages-substrate

relays/messages/src/message_race_delivery.rs
https://github.com/darwinia-network/bridger/issues/344
=> message_race_loop issue

Cargo.lock, relays/client-substrate/src/chain.rs, relays/client-substrate/src/client.rs, relays/client-substrate/src/lib.rs, relays/lib-substrate-relay/src/finality_pipeline.rs, relays/lib-substrate-relay/src/finality_target.rs, relays/lib-substrate-relay/src/headers_initialize.rs, relays/lib-substrate-relay/src/messages_lane.rs, relays/lib-substrate-relay/src/messages_source.rs, relays/lib-substrate-relay/src/messages_target.rs
Related: https://github.com/paritytech/parity-bridges-common/pull/1248
=> Try add SignParam

Cargo.lock, relays/messages/src/message_race_delivery.rs
=> Fix duplicate header relay

relays/messages/src/message_race_delivery.rs
Fix duplicate header relay for darwinia-v0.12.0
> wrong message for commit, it's pick from https://github.com/darwinia-network/darwinia-bridges-substrate/pull/12
Related #12
=> Pick from darwinia-network/darwinia-bridges-substrate#12

Cargo.lock, bin/runtime-common/Cargo.toml, bin/runtime-common/src/messages.rs, modules/parachains/Cargo.toml, modules/parachains/src/lib.rs, primitives/polkadot-core/src/parachains.rs, primitives/runtime/src/lib.rs
- Upstream PR: https://github.com/paritytech/parity-bridges-common/pull/1218
- And the commit: https://github.com/paritytech/parity-bridges-common/commit/6aece4f2327bb8c6e812b7913610f4fe93dc9bf9
- Add pangolin-parachain chain id: `pglp`
=> Update runtime-common to support parachain messages verification

relays/lib-substrate-relay/src/parachains_target.rs
Using `SignParam` delivers the params to follow the updates in branch darwinia-v0.12.1.
=> Fix parachain_target

relays/client-pangolin/src/runtime.rs, relays/client-pangoro/src/runtime.rs
Related: https://github.com/darwinia-network/bridger/pull/443
=> Add feemarket call for pangolin and pangoro runtime

primitives/chain-pangolin/src/lib.rs
[#38](https://github.com/darwinia-network/darwinia-bridges-substrate/issues/38)
=> Fix paras pallet name

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, bin/runtime-common/src/messages.rs, modules/fee-market/src/lib.rs, modules/fee-market/src/s2s/callbacks.rs, modules/fee-market/src/s2s/payment.rs, primitives/chain-pangolin/src/lib.rs, primitives/chain-pangoro/src/lib.rs, primitives/messages/src/lib.rs, rust-toolchain.toml
=> Add CI support for main branch

.github/workflows/ci.yml, rust-toolchain.toml
Pick from 
https://github.com/darwinia-network/darwinia-bridges-substrate/pull/41
=> Add CI Support for darwinia-v* branches

 rust-toolchain.toml, .github/workflows/ci.yml
=> Add CI support for polkadot-v* branches

primitives/chain-pangolin-parachain/src/lib.rs
`ToPangolinParachainParachainOutboundLaneApi_message_details` -> `ToPangolinParachainOutboundLaneApi_message_details`
=> Fix pangolin-parachain api name

modules/fee-market/src/benchmarking.rs
Fix pallet-fee-market benchmark.
=> Companion for `darwinia-v0.12.3`

modules/fee-market/src/lib.rs, modules/fee-market/src/s2s/callbacks.rs, modules/fee-market/src/s2s/payment.rs
The unit tests ensure no logic change. Just reorganize the code logic.
=> Rewrite `update_market()`

relays/client-crab/src/runtime.rs
https://github.com/darwinia-network/darwinia/blob/629c47111cbc7f96f8fce52dd0439fe07a8b4504/runtime/crab/src/lib.rs#L230
=> Fix call index in darwinia-v0.12.2

modules/dispatch/src/lib.rs
Just cherry-pick without modification.
=> Companion for #152

bin/runtime-common/src/messages.rs, modules/dispatch/src/lib.rs, modules/fee-market/src/tests.rs, modules/messages/src/inbound_lane.rs, modules/messages/src/lib.rs, primitives/message-dispatch/src/lib.rs
https://github.com/darwinia-network/darwinia-common/pull/1317 shows how to use the newly added `EveryThing` type. @04637
=> Companion for #155 (Parachain branch)

modules/grandpa/src/lib.rs
https://github.com/darwinia-network/darwinia-common/pull/1334
=> Public `WeightInfo` for grandpa

primitives/polkadot-core/src/parachains.rs
See https://github.com/darwinia-network/darwinia-common/commit/9fb46b8d83d08351d5eeecb063c8a6147f86cb7d
=> Add `PARAS_PALLET_NAME`

runtime-common/src/messages.rs
See https://github.com/darwinia-network/darwinia-common/pull/1469/commits/0ffb0e4cbf25acd87cf9afe0cd86273baba5ddc3
=> Add `FromThisChainMaximalOutboundPayloadSize`

runtime-common/src/integrity.rs, runtime-common/src/pallets.rs
Just cherry-pick without modification.  For this type of branch, I do not have push permissions.
=> Companion for 221

Cargo.lock, modules/dispatch/Cargo.toml, modules/dispatch/src/lib.rs, modules/fee-market/Cargo.toml, modules/grandpa/Cargo.toml, modules/grandpa/src/benchmarking.rs, modules/messages/Cargo.toml, modules/messages/src/inbound_lane.rs, modules/messages/src/lib.rs, modules/parachains/Cargo.toml, modules/parachains/src/lib.rs, primitives/darwinia-core/Cargo.toml, primitives/header-chain/Cargo.toml, primitives/header-chain/src/lib.rs, primitives/message-dispatch/Cargo.toml, primitives/messages/Cargo.toml, primitives/messages/src/lib.rs, primitives/parachains/Cargo.toml, primitives/polkadot-core/Cargo.toml, primitives/runtime/Cargo.toml, primitives/runtime/src/lib.rs, primitives/runtime/src/storage_proof.rs, primitives/test-utils/Cargo.toml, runtime-common/Cargo.toml
* Anchor polkadot-v0.9.32
* fix parity-util-mem conflict
* Anchor polkadot-v0.9.33
* Companion for paritytech/parity-bridges-common#1613
* Companion for paritytech/parity-bridges-common#1616
* Companion for paritytech/parity-bridges-common#1619
* Companion for paritytech/parity-bridges-common#1623
* Companion for paritytech/parity-bridges-common#1622
* Companion for paritytech/parity-bridges-common#1655
* Companion for paritytech/parity-bridges-common#1670
* Companion for paritytech/parity-bridges-common#1690
* Correct cargo
* Revert "Companion for paritytech/parity-bridges-common#1690"
This reverts commit 926b32dc3fa4820f418275bcc1b415121ac95f84.
* Revert "Companion for paritytech/parity-bridges-common#1670"
This reverts commit b96b41c1d487ea4f1c23e4128df32c7d3ec76760.
* Fix compile
* …
=> Pick polkadot-v0.9.33 to main

modules/dispatch/Cargo.toml, modules/fee-market/Cargo.toml, modules/grandpa/Cargo.toml, modules/messages/Cargo.toml, modules/parachains/Cargo.toml
See https://github.com/paritytech/parity-bridges-common/issues/1778
=> Enable `try-runtime` feature

modules/messages/src/lib.rs
Check out the comment I wrote.
=> Keep call index compatible

modules/messages/src/lib.rs
=> Fix call index (#243)

Cargo.lock, modules/dispatch/Cargo.toml, modules/fee-market/Cargo.toml, modules/grandpa/Cargo.toml, modules/messages/Cargo.toml, modules/messages/src/benchmarking.rs, modules/parachains/Cargo.toml, primitives/darwinia-core/Cargo.toml, primitives/header-chain/Cargo.toml, primitives/message-dispatch/Cargo.toml, primitives/messages/Cargo.toml, primitives/parachains/Cargo.toml, primitives/polkadot-core/Cargo.toml, primitives/runtime/Cargo.toml, primitives/test-utils/Cargo.toml, runtime-common/Cargo.toml, runtime-common/src/messages_benchmarking.rs
=> Prepare polkadot-v0.9.37 for Darwinia-2.0

Cargo.lock, modules/dispatch/Cargo.toml, modules/fee-market/Cargo.toml, modules/grandpa/Cargo.toml, modules/messages/Cargo.toml, modules/messages/src/benchmarking.rs, modules/parachains/Cargo.toml, primitives/darwinia-core/Cargo.toml, primitives/header-chain/Cargo.toml, primitives/message-dispatch/Cargo.toml, primitives/messages/Cargo.toml, primitives/parachains/Cargo.toml, primitives/polkadot-core/Cargo.toml, primitives/runtime/Cargo.toml, primitives/test-utils/Cargo.toml, runtime-common/Cargo.toml, runtime-common/src/messages_benchmarking.rs
* Anchor polkadot-v0.9.37
* Cargo update
* Fix compile runtime-benchmarks
* Format
=> Checkout polkadot-v0.9.37

.github/workflows/checks.yml
=> Add features compile check

primitives/darwinia-core/src/lib.rs, primitives/polkadot-core/src/lib.rs
=> Companions for updating darwina and polkadot config

Cargo.lock, modules/dispatch/src/lib.rs, modules/fee-market/Cargo.toml, modules/fee-market/src/mock.rs, modules/grandpa/Cargo.toml, modules/grandpa/src/mock.rs, modules/messages/Cargo.toml, modules/messages/src/benchmarking.rs, modules/messages/src/lib.rs, modules/messages/src/mock.rs, modules/messages/src/weights.rs, modules/messages/src/weights_ext.rs, modules/parachains/Cargo.toml, modules/parachains/src/mock.rs, modules/parachains/src/weights_ext.rs, runtime-common/Cargo.toml, runtime-common/src/lib.rs, runtime-common/src/messages.rs, runtime-common/src/messages_benchmarking.rs
Just cherry-pick, without touching files.
=> Companions for benchmark
